code/webSite/Areas/admin/Controllers/sys_ExlImportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace web.Areas.admin.Controllers.comm
{
    /// <summary>
    /// Excel导入和导出
    /// </summary>
    public class sys_ExlImportController : Controller
    {
        //展示导入界面
        [HttpGet]
        public ActionResult Import(string tableName)
        {
            ViewBag.TableName = tableName;
            return View();
        }

        //文件上传并读取到DataTable中
        [HttpPost]
        public JsonResult ImportUpload(string tableName)
        {
            try
            {
                string pathForSaving = "/upload/excelImport/" + tableName;
                rui.diskHelper.createDirectory(rui.webDiskHelper.getAbsolutePath(pathForSaving));
                List<string> pathList = rui.webDiskHelper.saveUploadFiles(pathForSaving, "Upload");
                if (pathList.Count > 0)
                {
                    DataTable table = rui.excelHelper.excelToDataTable(rui.webDiskHelper.getAbsolutePath(pathList[0]));
                    rui.sessionHelper.saveValue("importTable", table);
                    return Json(rui.jsonResult.getAJAXResult("上传成功", true), "text/html", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(rui.jsonResult.getAJAXResult("上传失败", false), "text/html", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                return Json(rui.jsonResult.getAJAXResult(ex.Message, false), "text/html", JsonRequestBehavior.AllowGet);
            }
        }

        //导入保存
        [HttpPost]
        public JsonResult SaveData(string tableName)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                
                //根据表名调用不用的数据保存方法
                db.bll.sys_ExlImport.importData(tableName);

                result.data = rui.jsonResult.getAJAXResult("数据保存成功！", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //展示导入数据
        public ActionResult disPlayImport()
        {
            return PartialView("disPlayImport");
        }
    }
}

code/webSite/Areas/admin/Views/sys_ExlImport/Import.cshtml
@{
    ViewBag.Title = "批量导入学生";
    string tableName = ViewBag.TableName;
}
@section header{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#fileupload").click(function () {
                var file = $("#Upload").val();
                if (isNull(file) == true) {
                    alert("请选择要上传的文件");
                    return false;
                } else {
                    if (checkFileType(file, ".xlsx")) {
                        var url = "/admin/sys_ExlImport/ImportUpload?tableName=@tableName";
                        fileUpload(url, "Upload", function (data) {
                            showJsonResult(data);
                            getTableAjax();
                        });
                    }
                }
            });
        });

        function getTableAjax() {
            ajaxHtml("/admin/sys_ExlImport/disPlayImport", {}, function (data) {
                $(".showData").html(data);
            });
        }
    </script>
}

@using (Html.BeginForm("ImportSave", "sys_ExlImport", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <form id="ajaxForms" enctype="multipart/form-data" method="post">
        <div class="container">
            <div class="search">
                <input type="file" name="Upload" id="Upload" />
                <a id="fileupload" class="opExlImport">上传并展示</a>
                @Html.ActionLink("保存到数据库", "SaveData", new { tableName=tableName }, new { @class = "billOp opSave", data_msg="确认保存？" })
                <a id="downfile" class="opExlExport" href='@string.Format("/upload/excelTemplate/{0}.xlsx",tableName)'>下载模板</a>
            </div>
            <div class="showData ruiTable">
            </div>
        </div>
    </form>
}

code/webSite/Areas/admin/Views/sys_ExlImport/disPlayImport.cshtml
@{
    System.Data.DataTable table = rui.sessionHelper.getValue<System.Data.DataTable>("importTable");
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <table style="width:100%;" id="showStudent">
        <thead>
            <tr class="even">
                @foreach (System.Data.DataColumn col in table.Columns)
                {
                    <th>@col.ColumnName</th>
                }
            </tr>
        </thead>
        @for (int i = 0; i < table.Rows.Count; i++)
        {
            <tr>
                @foreach (System.Data.DataColumn col in table.Columns)
                {
                    <td>@table.Rows[i][col.ColumnName]</td>
                }
            </tr>
        }
    </table>
}