code/webSite/Areas/admin/Controllers/sbs_MaterielController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Controllers;

namespace web.Areas.admin.Controllers
{
    /// <summary>
    /// 控制器-物料-性能测试表
    /// wzrui 2019-03-24
    /// </summary>
    public class sbs_MaterielController : baseController
    {
        public ActionResult Select(db.view.sbs_Materiel model)
        {
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showData", model);
            return View(model);
        }
    }
}

code/webSite/Areas/admin/Controllers/sys_PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Controllers;

namespace web.Areas.admin.Controllers
{
    /// <summary>
    /// 页面分页和列配置
    /// </summary>
    public class sys_PageController : baseController
    {
        //页面设置展示
        public ActionResult select(db.view.pageConfig model)
        {
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showData", model);
            return View(model);
        }

        //保存页面设置
        public JsonResult Update(string resourceCode,int cPageSize,int cPageWidth)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.sys_UcPage.update(resourceCode, cPageSize, cPageWidth, dc);
                result.data = rui.jsonResult.getAJAXResult("保存成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //页面设置重置
        public JsonResult reSet(string resourceCode)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.sys_UcPage.reSet(resourceCode, dc);
                result.data = rui.jsonResult.getAJAXResult("重置成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }
    }
}

code/webSite/Areas/admin/Views/sbs_Materiel/Select.cshtml
@model db.view.sbs_Materiel
@{
    ViewBag.Title = "物料-性能测试表";
    //wzrui 2019-03-24
}

@section header
{
    <script type="text/javascript">
        //刷新当前页面的数据
        function refleshData(exeCountSql) {
            $("#container").pager("reflesh", exeCountSql);
        }
        //初始化分页
        $(function () {
            $("#container").pager();
        });
    </script>
}
@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }
<div class="container" id="container" data-width="@Model.PageWidth" data-url="/admin/sbs_Materiel/Select">
    <div class="search">
        <span>物料编码：@Html.TextBoxFor(a => a.materielCode)</span>
    </div>
    <div class="toolbar">
        <a class="opSearch">查询</a>
        @Html.ActionLink("新增", "Insert", new { }, new { data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Insert), @class = "showDialogR opInsert" })
        @Html.ActionLink("定制", "select", "sys_Page", new { ResourceCode = Model.ResourceCode }, new { @class = "opPage showDialogRRM" })
    </div>
    <div class="pager"></div>
    <div class="showData layTable cbxCol">
        @{Html.RenderPartial("_ShowData");}
    </div>
</div>

code/webSite/Areas/admin/Views/sbs_Materiel/_ShowData.cshtml
@*数据展示的公用视图*@
@model rui.pagerBase
@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }
<input type="hidden" class="pagerinfo" data-rowcount="@Model.RowCount" data-pagesize="@Model.PageSize"
       data-pageindex="@Model.PageIndex" data-pagecount="@Model.PageCount"
       data-orderfield="@Model.OrderField" data-orderway="@Model.OrderWay" />
<table>
    <thead>
        <tr>
            @foreach (System.Data.DataRow row in Model.showColumn.Rows)
            {
                string colName = row["fieldCode"].ToString();
                if (row["isOrder"].ToString() == "True")
                {
                    <th data-option="@row["optionValue"]" data-field="@row["fieldCode"]" data-order="@Model.OrderWay">@row["fieldName"]@Html.orderColumn(Model.OrderField, Model.OrderWay, row["fieldCode"].ToString())</th>
                }
                else
                {
                    <th data-option="@row["optionValue"]">@row["fieldName"]</th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.dataTable.Rows.Count; i++)
        {
            string rowID = Model.dataTable.Rows[i]["rowID"].ToString();
            string keyCode = Model.dataTable.Rows[i][Model.keyField].ToString();
            <tr data-code="@keyCode">
                @foreach (System.Data.DataRow row in Model.showColumn.Rows)
                {
                    string colName = row["fieldCode"].ToString();
                    if (colName == "操作")
                    {
                        <td class="opRow">
                            @Html.ActionLink("详情", "Detail", new { rowID = rowID }, new { @class = "showDialog", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Detail) })
                            @Html.ActionLink("修改", "Update", new { rowID = rowID }, new { @class = "showDialogR", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Update) })
                            @Html.ActionLink("删除", "Delete", new { rowID = rowID }, new { @class = "listDelete", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Delete) })
                        </td>
                    }
                    else if("weight,gravity,length,unitPrice,quotaPrice,constValue,unitWeight,unitArea".IndexOf(colName)>=0)
                    {
                        <td>
                            @rui.typeHelper.va四舍五入(Model.dataTable.Rows[i][colName],2)
                        </td>
                    }
                    else
                    {
                        <td>
                            @Model.dataTable.Rows[i][colName]
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>