code/webSite/Areas/admin/Controllers/rbac_UserController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using System.Data;
using System.Web;
using web.Controllers;

namespace web.Areas.admin.Controllers
{
    /// <summary>
    /// 用户维护
    /// </summary>
    public class rbac_UserController : baseController
    {
        //搜索数据
        public ActionResult Select(db.view.rbac_User model)
        {
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showData", model);
            return View(model);
        }

        //展示详情
        public ActionResult Detail(string rowID)
        {
            db.rbac_User model = db.bll.rbac_User.getEntryByRowID(rowID, dc);
            model.relatedCode = string.Format("{0}({1})", db.bll.rbac_User.getNameByCode(model.relatedCode,dc), model.relatedCode);
            return View(model);
        }

        //展示新增
        [HttpGet]
        public ActionResult Insert()
        {
            db.rbac_User model = new db.rbac_User();
            return View(model);
        }

        //保存新增
        [HttpPost]
        public JsonResult Insert(db.rbac_User model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (ModelState.IsValid)
                {
                    string orgCode = db.bll.loginAdminHelper.getOrgCode();
                    string rowID = db.bll.rbac_User.createRelatedUser(model.userCode, model.userName, orgCode, model.deptCode, dc);
                    result.data = rui.jsonResult.getAJAXResult("新增成功", true,
                        rui.jsonResult.getDicByRowID(rowID));
                }
                else
                {
                    result.data = rui.jsonResult.getAJAXResult("输入不合法", false);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //展示更新
        [HttpGet]
        public ActionResult Update(string rowID)
        {
            db.rbac_User model = db.bll.rbac_User.getEntryByRowID(rowID, dc);
            return View(model);
        }

        //保存更新
        [HttpPost]
        public JsonResult Update(db.rbac_User model)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (ModelState.IsValid)
                {
                    db.bll.rbac_User.update(model, dc);
                    result.data = rui.jsonResult.getAJAXResult("更新成功", true);
                }
                else
                {
                    result.data = rui.jsonResult.getAJAXResult("输入不合法", false);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //删除
        [HttpPost]
        public JsonResult Delete(string rowID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                string keyCode = db.bll.rbac_User.getCodeByRowID(rowID,dc);
                db.bll.rbac_User.delete(keyCode,dc);
                result.data = rui.jsonResult.getAJAXResult("删除成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //重置密码
        public JsonResult ResetPW(string userCode)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                db.bll.rbac_User.resetPW(userCode,dc);
                result.data = rui.jsonResult.getAJAXResult("重置成功", true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //允许登录
        public JsonResult AllowLogin(string keyFieldValues)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                 string msg= db.bll.rbac_User.allowLogin(keyFieldValues,dc);
                 result.data = rui.jsonResult.getAJAXResult(msg, true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //取消登录
        public JsonResult CancelLogin(string keyFieldValues)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                 string msg = db.bll.rbac_User.noLogin(keyFieldValues,dc);
                 result.data = rui.jsonResult.getAJAXResult(msg, true);
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

        //权限查看
        /// <summary>
        /// 展示某用户拥有的所有权限
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult PrivShow(db.view.rbac_UserPriv model)
        {
            //获取登录用户可授权的模块
            model.moduleList = db.bll.loginAdminHelper.getPrivModule();

            List<SelectListItem> list = new List<SelectListItem>();

            //获取被授权用户拥有的模块
            {
                string userCode = db.bll.rbac_User.getCodeByRowID(model.rowID,dc);
                DataTable table = db.bll.privRbacHelper.getUserPrivModule(userCode, db.bll.loginAdminHelper.getOrgCode(), dc);
                foreach (var item in model.moduleList)
                {
                    DataRow[] rows = table.Select("moduleCode='" + item.Value + "'");
                    if (rows.Length != 0)
                    {
                        list.Add(item);
                    }
                        
                }
                model.moduleList = list;
            }

            //默认选中第一个模块
            if (string.IsNullOrEmpty(model.moduleCode) && model.moduleList.Count>0)
                model.moduleCode = model.moduleList[0].Value;

            model.isUser = true;
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showDataPriv", model);
            return View(model);
        }

        //授权
        /// <summary>
        /// 获取可授权模块列表和搜索模块下拥有的资源列表
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Priv(db.view.rbac_UserPriv model)
        {
            //获取登录用户可授权的模块
            model.moduleList = db.bll.loginAdminHelper.getPrivModule();

            //默认选中第一个模块
            if(string.IsNullOrEmpty(model.moduleCode))
                model.moduleCode = model.moduleList[0].Value;

            model.isUser = true;
            model.Search();
            if (rui.requestHelper.isAjax())
                return PartialView("_showDataPriv", model);
            return View(model);
        }

        //授权保存
        /// <summary>
        /// 首选获取本页所有资源编号
        /// 再通过资源编号获取每个资源所授予的操作权限和数据权限
        /// 将获取结果传递后业务层进行处理
        /// </summary>
        /// <param name="rowID"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Priv(string rowID)
        {
            rui.jsonResult result = new rui.jsonResult();
            try
            {
                if (ModelState.IsValid)
                {
                    //获取当前页的资源和每个资源勾选的权限列表
                    Dictionary<string, string> dicOP = new Dictionary<string, string>();
                    Dictionary<string, string> dicData = new Dictionary<string, string>();
                    List<string> list = rui.requestHelper.getList("resourceCodeList");
                    foreach (string keyCode in list)
                    {
                        //获取授权的操作
                        {
                            string value = rui.requestHelper.getMulValue(keyCode + "_cbx");
                            dicOP.Add(keyCode, rui.typeHelper.toString(value));  
                        }
                        //获取授权的数据权限(下拉框）
                        {
                            string value = rui.requestHelper.getValue(keyCode + "_ddl");
                            string dataPriv = rui.requestHelper.getValue(keyCode + "_dataPriv");
                            string haveDataPriv = rui.requestHelper.getValue(keyCode + "_haveDataPriv");
                            //当授权的数据权限大于被授权的数据权限时，允许更改客户的数据权限，否则不给修改
                            if (db.bll.privRbacHelper.compareDataPriv(dataPriv, haveDataPriv))
                                dicData.Add(keyCode, value);
                            else
                                dicData.Add(keyCode, haveDataPriv);
                        }
                    }
                    //保存所授权限
                    db.bll.rbac_UserPriv.savePriv(rowID,db.bll.loginAdminHelper.getOrgCode(), dicOP, dicData, dc);
                    result.data = rui.jsonResult.getAJAXResult("保存成功", true);
                }
                else
                {
                    result.data = rui.jsonResult.getAJAXResult("保存失败", false);
                }
            }
            catch (Exception ex)
            {
                rui.logHelper.log(ex);
                result.data = rui.jsonResult.getAJAXResult(rui.excptHelper.getExMsg(ex), false);
            }
            return Json(result.data);
        }

code/webSite/Areas/admin/Views/rbac_User/Detail.cshtml
@model db.rbac_User

@{
    ViewBag.Title = "Detail";
}
<div class="dialog">
    <div class="display-label hide">
        @Html.DisplayNameFor(model => model.rowID)
    </div>
    <div class="display-field hide">
        @Html.DisplayFor(model => model.rowID)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.userCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.userCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.userName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.userName)
    </div>

    <div class="display-label hide">
        @Html.DisplayNameFor(model => model.password)
    </div>
    <div class="display-field hide">
        @Html.DisplayFor(model => model.password)
    </div>

    <div class="display-label hide">
        @Html.DisplayNameFor(model => model.isAdmin)
    </div>
    <div class="display-field hide">
        @Html.DisplayFor(model => model.isAdmin)
    </div>

    <div class="display-label hide">
        @Html.DisplayNameFor(model => model.relatedCode)
    </div>
    <div class="display-field hide">
        @Html.DisplayFor(model => model.relatedCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.deptCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.deptCode)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.isLogin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.isLogin)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.remark)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.remark)
    </div>
    <p class="button">
        <a class="opClose">关闭</a>
    </p>
</div>

code/webSite/Areas/admin/Views/rbac_User/Insert.cshtml
@model db.rbac_User

@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="dialog">

        <div class="editor-label">
            @Html.LabelFor(model => model.userCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.userCode)
            @Html.ValidationMessageFor(model => model.userCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.userName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.userName)
            @Html.ValidationMessageFor(model => model.userName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.deptCode)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.deptCode, db.bll.sbs_Dept.bindDdl(true, true))
            @Html.ValidationMessageFor(model => model.deptCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.remark)
            @Html.ValidationMessageFor(model => model.remark)
        </div>

        <p class="button">
            <a class="billSave opSave" data-close="true">保存</a>
            <a class="opClose">关闭</a>
        </p>
    </div>
}

code/webSite/Areas/admin/Views/rbac_User/Priv.cshtml
@model db.view.rbac_UserPriv
@{
    ViewBag.Title = "用户授权";
}

@section header
{
    <style type="text/css">
    </style>
    <script type="text/javascript">
        //刷新当前页面的数据
        function refleshData(exeCountSql) {
            $("#container").pager("reflesh", exeCountSql);
        }
        //初始化分页
        $(function () {
            $("#container").pager();
        });
        $(document).ready(function () {
            //保存授权
            $("#opSavePriv").click(function () {
                //异步提交表单
                ajaxForm($("form"),function (data) {
                    showJsonResult(data);
                });
            });
            //模块切换
            $("#ddlModule").change(function () {
                $(".opSearch").trigger("click");
            });
            //表头的批量选择
            $(".showData").on("click", "thead :checkbox", function () {
                if ($(this).is(":checked"))
                    $(".showData tbody :checkbox").prop("checked", true);
                else
                    $(".showData tbody :checkbox").removeAttr("checked");
            });
            //行内的批量选择
            $(".showData").on("click", ".selectRow", function () {
                if ($(this).is(":checked"))
                    $(this).parents("tr").find(".opRow :checkbox").prop("checked", true);
                else
                    $(this).parents("tr").find(".opRow :checkbox").removeAttr("checked");
            });
        });
    </script>
}
<div class="container"  id="container" data-url="/admin/rbac_User/Priv">
    @using (Html.BeginForm("Priv", "rbac_User", FormMethod.Post, new { @class = "form-search form-inline", id = "formMain" }))
    {
        <div class="search">
            @Html.HiddenFor(a => a.rowID)
            <span>所属模块：@Html.DropDownListFor(a => a.moduleCode, Model.moduleList, new { id="ddlModule"})</span>
        </div>
        <div class="toolbar">
            <a class="opSearch">查询</a>
            @Html.ActionLink("保存", "Priv", new { }, new { @class = "opSave listBatchSave" })
        </div>
        <div class="pager"></div>
        <div class="showData">
            @{Html.RenderPartial("_ShowDataPriv");}
        </div>
    }
</div>

code/webSite/Areas/admin/Views/rbac_User/PrivShow.cshtml
@model db.view.rbac_UserPriv
@{
    ViewBag.Title = "用户授权";
}

@section header
{
    <style type="text/css">
    </style>
    <script type="text/javascript">
        //刷新当前页面的数据
        function refleshData(exeCountSql) {
            $("#container").pager("reflesh", exeCountSql);
        }
        //初始化分页
        $(function () {
            $("#container").pager();
        });
        $(document).ready(function () {
            //模块切换
            $("#ddlModule").change(function () {
                $(".opSearch").trigger("click");
            });
            //表头的批量选择
            $(".showData").on("click", "thead :checkbox", function () {
                if ($(this).is(":checked"))
                    $(".showData tbody :checkbox").prop("checked", true);
                else
                    $(".showData tbody :checkbox").removeAttr("checked");
            });
            //行内的批量选择
            $(".showData").on("click", ".selectRow", function () {
                if ($(this).is(":checked"))
                    $(this).parents("tr").find(".opRow :checkbox").prop("checked", true);
                else
                    $(this).parents("tr").find(".opRow :checkbox").removeAttr("checked");
            });
        });
    </script>
}
<div class="container" id="container" data-url="/admin/rbac_User/PrivShow">
    @using (Html.BeginForm("Priv", "rbac_User", FormMethod.Post, new { @class = "form-search form-inline", id = "formMain" }))
    {
        <div class="search">
            @Html.HiddenFor(a => a.rowID)
            <span>所属模块：@Html.DropDownListFor(a => a.moduleCode, Model.moduleList, new { id = "ddlModule" })</span>
        </div>
        <div class="toolbar">
            <a class="opSearch">查询</a>
        </div>
        <div class="pager"></div>
        <div class="showData">
            @{Html.RenderPartial("_ShowDataPriv");}
        </div>
    }
</div>

code/webSite/Areas/admin/Views/rbac_User/Select.cshtml
@model db.view.rbac_User

@{
    ViewBag.Title = "用户维护";
}

@section header
{
    <style type="text/css">
    </style>
    <script type="text/javascript">
        //刷新当前页面的数据
        function refleshData(exeCountSql) {
            $("#container").pager("reflesh", exeCountSql);
        }
        //初始化分页
        $(function () {
            $("#container").pager();
        });

       $(document).ready(function () {
            $(".listBatchOpPost").click(function () {
                var postCode = $(".postCode").val();
                if (isNull(postCode) == false) {
                    listBatchOp($(this), "postCode=" + postCode);
                } else {
                    showInfo("请选择任职职务");
                }
                return false;
            });
        });
    </script>
}
@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }
<div class="container" id="container" data-width="@Model.PageWidth" data-url="/admin/rbac_User/select">
    <div class="search">
        <span>所属部门：@Html.DropDownListFor(a => a.deptCode, db.bll.sbs_Dept.bindDdl(true, true))</span>
        <span>用户编码：@Html.TextBoxFor(a => a.userCode)</span>
        <span>用户名称：@Html.TextBoxFor(a => a.userName)</span>
        <span>可登录：@Html.DropDownListFor(a => a.isLogin, rui.listHelper.bind是否(true))</span>
    </div>
    <div class="toolbar">
        <a class="opSearch">查询</a>
        @Html.ActionLink("新增", "Insert", new { }, new { @class = "showDialogR opInsert", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Insert) })
        <span>
            选择职务:@Html.DropDownList("postCode", db.bll.af_AuditPost.bindDdl(false), new { @class = "postCode" })
            @Html.ActionLink("审批职务任职", "userBatchPost", "af_AuditPostUser", new { }, new { @class = "listBatchOpPost opBtn", data_show = rui.privCtl.isPriv(ctrl, "userBatchPost"), data_msg = "确认批量设定任职？" })
        </span>
        @Html.ActionLink("允许登录", "allowLogin", new { }, new { @class = "listBatchOp opBtn", data_show = rui.privCtl.isPriv(ctrl, "allowLogin"), data_msg = "确认允许登录？" })
        @Html.ActionLink("取消登录", "cancelLogin", new { }, new { @class = "listBatchOp opBtn", data_show = rui.privCtl.isPriv(ctrl, "cancelLogin"), data_msg = "确认取消登录？" })
    </div>

    <div class="pager"></div>
    <div class="showData cbxCol">
        @{Html.RenderPartial("_ShowData");}
    </div>
</div>

code/webSite/Areas/admin/Views/rbac_User/Update.cshtml
@model db.rbac_User

@{
    ViewBag.Title = "Update";
}

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="dialog">
        <div class="editor-label hide">
            @Html.LabelFor(model => model.rowNum)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.rowNum)
            @Html.ValidationMessageFor(model => model.rowNum)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.userCode)
        </div>
        <div class="editor-field read">
            @Html.EditorFor(model => model.userCode)
            @Html.ValidationMessageFor(model => model.userCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.userName)
        </div>
        <div class="editor-field read">
            @Html.EditorFor(model => model.userName)
            @Html.ValidationMessageFor(model => model.userName)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.password)
        </div>
        <div class="editor-field hide">
            @Html.EditorFor(model => model.password)
            @Html.ValidationMessageFor(model => model.password)
        </div>

        <div class="editor-label hide">
            @Html.LabelFor(model => model.relatedCode)
        </div>
        <div class="editor-field read hide">
            @Html.TextBox("emplInfo", string.Format("{0}({1})", db.bll.rbac_User.getNameByCode(Model.relatedCode, db.efHelper.newDc()), Model.relatedCode))
            @Html.HiddenFor(model => model.relatedCode)
            @Html.ValidationMessageFor(model => model.relatedCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.deptCode)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.deptCode, db.bll.sbs_Dept.bindDdl(true, true))
            @Html.ValidationMessageFor(model => model.deptCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.isLogin)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.isLogin, rui.listHelper.bind是否(true))
            @Html.ValidationMessageFor(model => model.isLogin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.remark)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.remark)
            @Html.ValidationMessageFor(model => model.remark)
        </div>

        <p class="button">
            <a class="billSave opSave" data-close="true">保存</a>
            <a class="opClose">关闭</a>
        </p>
    </div>
}

code/webSite/Areas/admin/Views/rbac_User/_ShowData.cshtml
@*数据展示的公用视图*@
@model rui.pagerBase
@{ string ctrl = ViewContext.RouteData.Values["controller"].ToString(); }

<input type="hidden" class="pagerinfo" data-rowcount="@Model.RowCount" data-pagesize="@Model.PageSize"
       data-pageindex="@Model.PageIndex" data-pagecount="@Model.PageCount"
       data-orderfield="@Model.OrderField" data-orderway="@Model.OrderWay" />
<table>
    <thead>
        <tr>
            @foreach (System.Data.DataRow row in Model.showColumn.Rows)
            {
                string colName = row["fieldCode"].ToString();
                if (row["isOrder"].ToString() == "True")
                {
                    <th data-option="@row["optionValue"]" data-field="@row["fieldCode"]" data-order="@Model.OrderWay">@row["fieldName"]@Html.orderColumn(Model.OrderField, Model.OrderWay, row["fieldCode"].ToString())</th>
                }
                else
                {
                    <th data-option="@row["optionValue"]">@row["fieldName"]</th>
                }
            }
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.dataTable.Rows.Count; i++)
        {
            string rowID = Model.dataTable.Rows[i]["rowID"].ToString();
            string keyCode = Model.dataTable.Rows[i][Model.keyField].ToString();
            <tr data-code="@keyCode">
                @foreach (System.Data.DataRow row in Model.showColumn.Rows)
                {
                    string colName = row["fieldCode"].ToString();
                    if (colName == "操作")
                    {
                        <td class="opRow">
                            @Html.ActionLink("详情", "Detail", new { rowID = rowID }, new { @class = "showDialog", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Detail) })
                            @Html.ActionLink("修改", "Update", new { rowID = rowID }, new { @class = "showDialogR", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Update) })
                            @Html.ActionLink("删除", "Delete", new { rowID = rowID }, new { @class = "listDelete", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Delete) })
                            @Html.ActionLink("授权", "Priv", new { rowID = rowID }, new { @class = "showDialog", data_show = (db.bll.loginAdminHelper.getUserCode() != keyCode) && @rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.Priv) })
                            @Html.ActionLink("重置密码", "resetPW", new { userCode = keyCode }, new { @class = "listOp", data_msg = "确认重置？", data_show = rui.privCtl.isPriv(ctrl, rui.privCtl.eOp.resetPW) })
                            @Html.ActionLink("权限列表", "PrivShow", new { rowID = rowID }, new { @class = "showDialog", data_show = rui.privCtl.isPriv(ctrl, "PrivList") })
                        </td>
                    }
                    else
                    {
                        <td>@Model.dataTable.Rows[i][colName]</td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

code/webSite/Areas/admin/Views/rbac_User/_ShowDataPriv.cshtml
@model rui.pagerBase
<input type="hidden" class="pagerinfo" data-rowcount="@Model.RowCount" data-pagesize="@Model.PageSize"
       data-pageindex="@Model.PageIndex" data-pagecount="@Model.PageCount"
       data-orderfield="@Model.OrderField" data-orderway="@Model.OrderWay" />
<style type="text/css">
    .opRow span {
        display: inline-block;
        margin-right: 5px;
    }

    .opRow input {
        margin-left: 1px;
    }
</style>
<table>
    <thead>
        <tr>
            @foreach (System.Data.DataRow row in Model.showColumn.Rows) {
                if (row["isOrder"].ToString() == "True") {
                    <th data-option="@row["optionValue"]" data-field="@row["fieldCode"]" data-order="@Model.OrderWay">@row["fieldName"]@Html.orderColumn(Model.OrderField, Model.OrderWay, row["fieldCode"].ToString())</th>
                } else {
                    <th data-option="@row["optionValue"]">@row["fieldName"]</th>
                }
            }
            <th class="cbxtd">
                <input type="checkbox" />
            </th>
            <th style="width:50%">
                按钮权限
            </th>
            <th>数据权限</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.dataTable.Rows.Count; i++)
        {
            string rowID = Model.dataTable.Rows[i]["rowID"].ToString();
            string keyCode = Model.dataTable.Rows[i][Model.keyField].ToString();
            <tr data-code="@keyCode">
                @foreach (System.Data.DataRow row in Model.showColumn.Rows) {
                    <td>@Model.dataTable.Rows[i][row["fieldCode"].ToString()]</td>
                }
                <td class="cbxtd" style="width:26px;text-align:center;">
                    <input type="checkbox" class="selectRow" />
                </td>
                <td class="opRow">
                    <!--资源编号-->
                    @Html.Hidden("resourceCodeList", Model.dataTable.Rows[i][Model.keyField])
                    @Html.CheckBoxListPriv(keyCode + "_cbx", Model.dataTable.Rows[i]["opPriv"].ToString(),
                         Model.dataTable.Rows[i]["haveOpPriv"].ToString(), db.bll.rbac_ResourceOp.bindDdl(keyCode))
                </td>
                <td>
                    <!--登录用户拥有的数据权限-->
                    @Html.Hidden(keyCode + "_dataPriv", Model.dataTable.Rows[i]["dataPriv"])
                    <!--被授权用户拥有的数据权限-->
                    @Html.Hidden(keyCode + "_haveDataPriv", Model.dataTable.Rows[i]["haveDataPriv"])
                    <!--数据权限下拉框，当拥有的小于被授权用户拥有的时候，隐藏下拉框-->
                    @Html.DropDownList(keyCode + "_ddl", db.bll.rbac_DataPriv.bindDdl(Model.dataTable.Rows[i]["dataPriv"].ToString(),
                            Model.dataTable.Rows[i]["haveDataPriv"].ToString(), false),
                        new
                        {
                            data_show = (Model.dataTable.Rows[i]["dataControl"].ToString() == "是" &&
                                db.bll.privRbacHelper.compareDataPriv(Model.dataTable.Rows[i]["dataPriv"].ToString()
                                , Model.dataTable.Rows[i]["haveDataPriv"].ToString()))
                        })
                </td>
            </tr>
        }
    </tbody>
</table>